// UiBindingSnapshotTests.cs
//
// The guarantee behind the page-by-page UI overhaul: nothing a page DOES can disappear by
// accident. For every XAML file this records each binding path, event handler and named
// element, with how many times it appears, into a committed baseline. The test then fails if
// any of those counts ever drops.
//
// Adding is always fine. Removing something on purpose means editing the baseline in the same
// commit, which makes every removal a visible, deliberate decision instead of a silent one.
//
// To regenerate after an intended change:
//   set SYSTEMA_WRITE_UI_BASELINE=1 && dotnet test --filter UiBindingSnapshotTests
// then review the baseline diff line by line before committing it.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Xunit;

namespace Systema.Tests;

public class UiBindingSnapshotTests
{
    private static string RepoRoot()
    {
        var asmDir = Path.GetDirectoryName(typeof(UiBindingSnapshotTests).Assembly.Location)!;
        return Path.GetFullPath(Path.Combine(asmDir, "..", "..", "..", "..", ".."));
    }

    private static string BaselinePath() =>
        Path.Combine(RepoRoot(), "tests", "Systema.Tests", "Baselines", "ui-bindings.txt");

    private static readonly Regex Comment = new("<!--.*?-->", RegexOptions.Singleline);

    // {Binding Foo.Bar, ...} and {Binding Path=Foo.Bar, ...}
    private static readonly Regex MarkupBinding =
        new(@"\{Binding\s+(?:Path=)?([A-Za-z_][A-Za-z0-9_.\[\]]*)");
    // <Binding Path="Foo" .../> inside MultiBinding
    private static readonly Regex ElementBinding = new(@"<Binding\s+Path=""([^""]+)""");
    private static readonly Regex Handler = new(
        @"\b(Click|Checked|Unchecked|Loaded|Unloaded|SelectionChanged|TextChanged|MouseLeftButtonDown|" +
        @"MouseLeftButtonUp|PreviewMouseLeftButtonDown|PreviewMouseLeftButtonUp|KeyDown|PreviewKeyDown|" +
        @"ValueChanged|IsVisibleChanged|GotFocus|LostFocus|DropDownOpened|DropDownClosed|Activated|" +
        @"Deactivated|SizeChanged|MouseEnter|MouseLeave|PreviewMouseWheel|RequestNavigate|Closing|Closed|" +
        @"ContextMenuOpening|MouseDoubleClick|PreviewTextInput)=""([A-Za-z_][A-Za-z0-9_]*)""");
    private static readonly Regex Name = new(@"x:Name=""([^""]+)""");

    /// <summary>atom -> count for one XAML file.</summary>
    internal static Dictionary<string, int> Atoms(string xaml)
    {
        xaml = Comment.Replace(xaml, "");
        var counts = new Dictionary<string, int>(StringComparer.Ordinal);
        void Add(string a) => counts[a] = counts.TryGetValue(a, out int n) ? n + 1 : 1;

        foreach (Match m in MarkupBinding.Matches(xaml))  Add("binding " + m.Groups[1].Value);
        foreach (Match m in ElementBinding.Matches(xaml)) Add("binding " + m.Groups[1].Value);
        foreach (Match m in Handler.Matches(xaml))        Add($"handler {m.Groups[1].Value}={m.Groups[2].Value}");
        foreach (Match m in Name.Matches(xaml))           Add("name " + m.Groups[1].Value);
        return counts;
    }

    private static SortedDictionary<string, int> Current()
    {
        var all = new SortedDictionary<string, int>(StringComparer.Ordinal);
        string views = Path.Combine(RepoRoot(), "src", "Systema", "Views");
        foreach (var file in Directory.GetFiles(views, "*.xaml").OrderBy(f => f, StringComparer.Ordinal))
            foreach (var (atom, n) in Atoms(File.ReadAllText(file)))
                all[$"{Path.GetFileName(file)} | {atom}"] = n;
        return all;
    }

    [Fact]
    public void NothingAPageDoesHasDisappeared()
    {
        var current = Current();

        if (Environment.GetEnvironmentVariable("SYSTEMA_WRITE_UI_BASELINE") == "1")
        {
            Directory.CreateDirectory(Path.GetDirectoryName(BaselinePath())!);
            var sb = new StringBuilder();
            sb.AppendLine("# Generated by UiBindingSnapshotTests. One line per page atom: file | kind name | count.");
            sb.AppendLine("# A count may rise freely. Lowering or deleting a line is a deliberate removal: say why in the commit.");
            foreach (var (k, n) in current) sb.AppendLine($"{k} | {n}");
            File.WriteAllText(BaselinePath(), sb.ToString());
            return;
        }

        Assert.True(File.Exists(BaselinePath()), "UI binding baseline is missing: " + BaselinePath());

        var lost = new List<string>();
        foreach (var raw in File.ReadAllLines(BaselinePath()))
        {
            if (raw.Length == 0 || raw.StartsWith('#')) continue;
            int cut = raw.LastIndexOf(" | ", StringComparison.Ordinal);
            string key = raw[..cut];
            int want = int.Parse(raw[(cut + 3)..]);
            int have = current.TryGetValue(key, out int h) ? h : 0;
            if (have < want) lost.Add($"{key}  (was {want}, now {have})");
        }

        Assert.True(lost.Count == 0,
            "Something a page did has disappeared. If that was intended, regenerate the baseline and justify it:\n  " +
            string.Join("\n  ", lost));
    }

    // The extractor has to actually see things, or the test above would pass on nothing.
    [Fact]
    public void Extractor_FindsBindingsHandlersAndNames()
    {
        var a = Atoms(@"<Grid x:Name=""Root""><!-- {Binding Ignored} -->
            <CheckBox IsChecked=""{Binding Path=Foo.Bar, Mode=TwoWay}"" Click=""OnClick""/>
            <TextBlock Text=""{Binding Title}""/><TextBlock Text=""{Binding Title}""/>
            <MultiBinding><Binding Path=""DataContext.ActiveSection""/></MultiBinding></Grid>");
        Assert.Equal(1, a["binding Foo.Bar"]);
        Assert.Equal(2, a["binding Title"]);
        Assert.Equal(1, a["binding DataContext.ActiveSection"]);
        Assert.Equal(1, a["handler Click=OnClick"]);
        Assert.Equal(1, a["name Root"]);
        Assert.False(a.ContainsKey("binding Ignored"));
    }
}
